sonar.projectKey=usv_events_frontend
sonar.projectName=USV Events - Frontend
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# Frontend - JavaScript/React
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/__tests__/**
sonar.inclusions=**/*.js,**/*.jsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/.venv/**,**/coverage/**

# JavaScript
sonar.javascript.file.suffixes=.js,.jsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Security
sonar.security.hotspots.disabled=false
