sonar.projectKey=usv_events_backend
sonar.projectName=USV Events - Backend
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# Backend - Python
sonar.sources=app
sonar.tests=tests
sonar.inclusions=**/*.py
sonar.exclusions=**/tests/**,**/__pycache__/**,**/.venv/**,**/venv/**

# Python
sonar.python.file.suffixes=.py
sonar.python.coverage.reportPath=coverage.xml

# Security
sonar.security.hotspots.disabled=false
